apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-service-rel-1-0-0
  namespace: processor
  labels:
    app: cms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-service
  template:
    metadata:
      name: cms-service-rel-1-0-0
      labels:
        app: cms-service
      annotations:
        prometheus.io.scrape: 'false'
    spec:
      containers:
        - name: cms-service-rel-1-0-0
          image: actio.azurecr.io/cms-service-rel-1-0-0:1.0.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
	  imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: frmpullsecret
      schedulerName: default-scheduler
      enableServiceLinks: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
